services:
  mt_frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mt_frontend
    restart: unless-stopped
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - NODE_ENV=production
      - PORT=3000
    ports:
      - "3000:3000"
